### ISSUE TITLE
你好,可以分享编译好了的程序吗?感谢了.

### ISSUE THREAD

**Issue by min704** [asiontang/93.Ye.M3U8.Downloader#1]
小众上看到gitee上附件没数据了,不知可否分享下了,感谢了!~

**Comment by asiontang** [comment]
试试新版本:[v190603.01.60.060 · AsionTang/93.Ye.M3U8.Downloader - 码云 Gitee.com](https://gitee.com/AsionTang/93.Ye.M3U8.Downloader/releases/v190603.01.60.060)
